/hst:hst/hst:configurations/myproject/hst:workspace/hst:containers/productlist/main/productlist:
  .meta:order-before: banner
  jcr:primaryType: hst:containeritemcomponent
  hst:componentclassname: org.example.components.ProductListComponent
  hst:iconpath: images/catalog-component-icons/product-list.png
  hst:label: Product List
  hst:parameternames: [isHideOutOfStock, path, documentTypes, sortOrder, sortField,
    pageSize, showPagination, includeSubtypes]
  hst:parametervalues: ['on', '', '', desc, '', '5', 'on', 'on']
  hst:template: productlist-main
